### ISSUE TITLE
Documentation: Write man pages for all executable programs in bin

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/temp-test-ioccc#2009]
# TODO

* [ ] Write man pages for executable programs in bin

The executable programs (shell scripts, awk scripts, executable binaries?) need to have man pages written for them.  Perhaps such man pages should go under a top level directory called "/man".

**Comment by xexyl** [comment]
Please assign this. And obviously the first one I should write is the ioccc status one since I wrote that tool!

**Comment by xexyl** [comment]
I feel like I should do the man page for that tool even before I continue with 3. Not sure I can do that right now but I hope to do it in a bit if not now. Yes I know it's not high priority but I like to be complete.

**Comment by xexyl** [comment]
Done with the man page for the status tool but I have to go afk for a little bit. When I am back I will commit it with some fixes in the script included. 

Then I will get back to 3. I think that for the shellcheck warnings that are disabled already I will return to correcting the comments but .. hmm perhaps not: if I do that it will be harder to keep track of which ones need to be reviewed. Well no: I will update the todo file to note it. 

Today is a busier day so I will have less time but I should be able to finish a number of entries anyway. Hopefully I can finish 2006. I believe that I can. 

So after committing the updates for this issue I will update the todo file and then look at 3 again. I don't think I will be able to rest but if I can I will. 

But at least I get to listen to the rain! It's a rare treat and all the more since it's still raining!

**Comment by xexyl** [comment]
Although a different repo this issue reminds me that I still have not written a man page for `jprint(1)`! I guess when I do this issue I can work on that. Perhaps you could add this to the todo file (or a note in the OP)? Thanks!

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by xexyl** [comment]
I see yesterday that you deleted the man page. How funny that I almost did that very thing yesterday!

I will reply to the manifest comments and then do other things. I don't think I'll be doing anything until at least Friday as the next two days (starting tomorrow) will be very hard and a lot of time away from any computer.

**Comment by lcn2** [comment]
For the moment we are simply using `bin/README.md` to document bin tool usage, generating `bin/index.html` to view.   Is that enough to warrant consideration of closing this issue?

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by xexyl** [comment]
> # QUESTION
> For the moment we are simply using `bin/README.md` to document bin tool usage, generating `bin/index.html` to view. Is that enough to warrant consideration of closing this issue?

Good question. It might. It would certainly speed things up. And since very few people will need to use the tools - and this will be even more true once the merge happens (I think?) - it might be that man pages are not actually needed.

This would also speed things up. Plus it would be good to have another issue resolved - even if it ended up being different from what was planned.

**Comment by lcn2** [comment]
> > # QUESTION
> > For the moment we are simply using `bin/README.md` to document bin tool usage, generating `bin/index.html` to view. Is that enough to warrant consideration of closing this issue?
> 
> Good question. It might. It would certainly speed things up. And since very few people will need to use the tools - and this will be even more true once the merge happens (I think?) - it might be that man pages are not actually needed.
> 
> This would also speed things up in multiple ways, even. Plus it would be good to have another issue resolved - even if it ended up being different from what was planned.

We will close this issue with a suggestion that the `bin/README.md` be reviewed and improved if/as needed given that there won't be any man pages for these `bin` commands.

**Comment by xexyl** [comment]
> > > # QUESTION
> > > For the moment we are simply using `bin/README.md` to document bin tool usage, generating `bin/index.html` to view. Is that enough to warrant consideration of closing this issue?
> > 
> > 
> > Good question. It might. It would certainly speed things up. And since very few people will need to use the tools - and this will be even more true once the merge happens (I think?) - it might be that man pages are not actually needed.
> > This would also speed things up in multiple ways, even. Plus it would be good to have another issue resolved - even if it ended up being different from what was planned.
> 
> We will close this issue with a suggestion that the `bin/README.md` be reviewed and improved if/as needed given that there won't be any man pages for these `bin` commands.

If you would like me to help with that perhaps you can add it as part of the todo to #2006 - since that's about content of the web pages (even if it's more about making sure it is displayed right)? Or if you prefer somewhere else you can do that too. 

Given too that there are new tools I will have to look at it anyway but it might help with a note.
