### ISSUE TITLE
Bug: Corrections, formatting, suggestions for Guidelines.

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/temp-test-ioccc#2511]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like it

### Describe the problem

***Formatting***

```
* that mandate the exclusive the use of an specific Integrated
* Development Environment (IDE)
``` 

### What you expect

I think you meant:
```
* that mandate the exclusive the use of an specific Integrated Development Environment (IDE)
``` 

### Environment

```markdown
- OS:
- Device:
- Browser:
```

### Anything else?

Have I mentioned how I hate templates, preferring a more open free form report.  (Good) developers know what back ground (front not with standing) is needed for a suitable report.

**Comment by lcn2** [comment]
Fixed in commit f8a2c9defce7edcc790d2b8072e9c4cbd46d0842 

Thank you @SirWumpus for your bug report.  We appreciate your time and attention to the guidelines.

# Suggestion / Request

Continue to look at the `next/rules.html` and `next/guidelines.html`.  Your remarks in the past have been **very much appreciated** and will contribute to a better IOCCC28.

# p.s.

> Have I mentioned how I hate templates, preferring a more open free form report. (Good) developers know what back ground (front not with standing) is needed for a suitable report.

We offer two++ suggestions in your case:

0) edit the resulting template as needed
b) continue to have fun with the "Anything else?" section .. we don't mind
II) just open a pull request and put your good development experience into the pull request remarks

**Comment by SirWumpus** [comment]
Not to worry.  I continue picking things apart.

**Comment by xexyl** [comment]
I pulled this change on the server a bit ago and will start doing a technical review as you asked me to do, soon, btw.

**Comment by xexyl** [comment]
Rules corrected in many ways, mostly technical.

Guidelines next .. but not until later today - or tomorrow.

**Comment by xexyl** [comment]
> # p.s.
> > Have I mentioned how I hate templates, preferring a more open free form report. (Good) developers know what back ground (front not with standing) is needed for a suitable report.
> 
> We offer two++ suggestions in your case:
> 
> 0. edit the resulting template as needed
>    b) continue to have fun with the "Anything else?" section .. we don't mind
>    II) just open a pull request and put your good development experience into the pull request remarks

Make a third suggestion: 

0. Templates make it easier to sort through and since we **do** give the 'anything else' possibility if you really wanted to you could put everything there .. though that does seem silly to me and kind of defeats the purpose.

BTW: did you ever think about how they say that C++'s name is that it's better than C but how it's hardly true? I am sure you have but here's something they did not think of: the value of `C++` is actually C but as a side effect `C` is increased by 1: thus it's definitely not better! Actually a better name would have been `--C` but I won't get into that :-)

**Comment by xexyl** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched for existing issues and did not find anything like it
> 
> ### Describe the problem
> _**Formatting**_
> 
> ```
> * that mandate the exclusive the use of an specific Integrated
> * Development Environment (IDE)
> ```
> 
> ### Relevant images, screenshots or other files
> _No response_
> 
> ### What you expect
> I think you meant:
> 
> ```
> * that mandate the exclusive the use of an specific Integrated Development Environment (IDE)
> ```
> 

I think what is **REALLY** meant is:

* that mandate the exclusive use of a specific Integrated Development Environment (IDE)

(.. or depending on what comes before it `that MANDATES`)

:-)

... which I will fix it when I work on it next.

**Comment by xexyl** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched for existing issues and did not find anything like it
> > 
> > ### Describe the problem
> > _**Formatting**_
> > ```
> > * that mandate the exclusive the use of an specific Integrated
> > * Development Environment (IDE)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Relevant images, screenshots or other files
> > _No response_
> > ### What you expect
> > I think you meant:
> > ```
> > * that mandate the exclusive the use of an specific Integrated Development Environment (IDE)
> > ```
> 
> I think what is **REALLY** meant is:
> 
> * that mandate the exclusive use of a specific Integrated Development Environment (IDE)
> 
> (.. or depending on what comes before it `that MANDATES`)
> 
> :-)
> 
> ... which I will fix it when I work on it next.

Okay fixed .. now back later today .. or tomorrow.

**Comment by xexyl** [comment]
Actually I see a slight improvement is in order in the template too, grammar wise. Well I can worry about that later.

**Comment by xexyl** [comment]
Okay I fixed the templates too. As commit https://github.com/ioccc-src/temp-test-ioccc/pull/2516/commits/6c92038be01146a38d69db1bff0e3612402aefde says, quite ironically:

    Minor grammar improvement in issue templates
    
    .. though this certainly can be improved some still, the entire wording
    of the sentence. That will be considered later.
    
    Thank you to @SirWumpus for indirectly making me aware of this: I know
    he hates templates so I feel like I should thank him specially :-)

I hope you appreciate that .. it's all in good fun of course! Now I really am going afk! I have to make this change in the other repo though ... will do that when back.

**Comment by xexyl** [comment]
> > ... they say that C++'s name is that it's better than C ...
> 
> At my first place of work (after UNI) with MKS, some of the developers would say `C++ is the Cobol of the 1990's`.

I'm sure there are a lot of jokes about C++. That one I thought of years ago but the one you share is a good one too.

In the man pages of the mkiocccentry repo we have in comments:

```
.\" Humour impairment is not virtue nor is it a vice, it's just plain
.\" wrong: almost as wrong as JSON spec mis-features and C++ obfuscation! :-)
.\"
```

There's another fun thing to discover in them and at least one has something else fun, all in comments.

**Comment by xexyl** [comment]
Also there's a funny poem/verse about another programming language of old. I can't remember which one. I think it's in flex and bison 2nd edition but I might be wrong. It's been a while since I've read it.

I think also someone said something like: `In many ways, Java is C--`. I would disagree with that. It's certainly far from my favourite language but one thing is nice - it's graphics API. There are plenty of things I don't like about it but I'm not an expert it in it either. I much prefer it to C++ though (although I've written entire applications in C++ .. I just found that I started to do what I call C-ify it - make things more like C).
