### ISSUE TITLE
Links in Rules & Guidelines - Markdown vs HTML

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/temp-test-ioccc#2535]
There is some *inconsistency* with Markdown links: 

1. Should relative links in `next/rules.md` and `next/guidelines.md` refer to a markdown `.md` file or be allowed to cross-over to a `.html` version ***when a markdown version is present***?

2. Should there be Markdown `.md` equivalents for all `.html` files?  ***Begs the question should we be concerned with `.html` files at all?***  GitHub will render the `.md` and they are intended to be read also as plain text with `more(1)` or one's favourite editor.  Many browsers have Markdown extensions (FYI for Firefox I use [Markdown Viewer Webext](https://github.com/Cimbali/markdown-viewer) or [GitLab Markdown Viewer](https://github.com/painyeph/GitLabMarkdownViewer) ).

3. Maintaining duplicate `.html` files (even if generated) feels very much like a bad idea.

## Some examples

* > Watch both \[the IOCCC status page]\(https://github.com/ioccc-src/temp-test-ioccc/blob/master/status.html)  

`status.md` exists

* > receive prior permission in writing by \[contacting the judges]\(https://github.com/ioccc-src/temp-test-ioccc/blob/master/contact.html).  

`contact.md` exists

* > These \[IOCCC guidelines]\(https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/guidelines.html) are version  

`guidelines.md` exists

* > IMPORTANT: Be SURE to read the \[IOCCC rules]\(https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/rules.html).  

`next/rules.md` exists

* > The \[Rule 2a]\(https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/rules.html#rule2a) size has increased from  

`next/rules.md` exists - I do not recall any Markdown syntax for anchors like `#rule2a`, so it should just point to the `rules.md` , viewer left to scroll (if no contents table is generated).

* > The \[Rule 2b]\(https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/rules.html#rule2b) size has increased from  

Similar to above point.

The above are just some of the links I found while reviewing `next/guidelines.md` just at the start!  I think this issue pervades throughout.

- - -
`Don't be the missing link.`

**Comment by xexyl** [comment]
> There is some _inconsistency_ with Markdown links:
> 

Not sure of this but I'll see if I can help out (though it should be noted that not all have been looked at yet either).

> 1. Should relative links in `next/rules.md` and `next/guidelines.md` refer to a markdown `.md` file or be allowed to cross-over to a `.html` version _**when a markdown version is present**_?

The rule is that if there is a html file then the link should refer to the html file.

> 2. Should there be Markdown `.md` equivalents for all `.html` files?  _**Begs the question should we be concerned with `.html` files at all?**_  GitHub will render the `.md` and they are intended to be read also as plain text with `more(1)` or one's favourite editor.  Many browsers have Markdown extensions (FYI for Firefox I use [Markdown Viewer Webext](https://github.com/Cimbali/markdown-viewer) or [GitLab Markdown Viewer](https://github.com/painyeph/GitLabMarkdownViewer) ).


No there should not be: some html files in some entries are provided by the author that cannot be generated by markdown.

And the html is for the official website. GitHub does render it but it wouldn't work for the above referred to html files (for example) and the html files look much nicer too.

> 3. Maintaining duplicate `.html` files (even if generated) feels very much like a bad idea.
> 

If they're generated by markdown they aren't duplicate - we just have to run the right rules to update them.

> ## Some examples
> * > Watch both [the IOCCC status page](https://github.com/ioccc-src/temp-test-ioccc/blob/master/status.html)
> 
> `status.md` exists

Yes but the markdown files, when generated to html, then link to the html files. See https://ioccc-src.github.io/temp-test-ioccc/index.html for the actual page.

> 
> * > receive prior permission in writing by [contacting the judges](https://github.com/ioccc-src/temp-test-ioccc/blob/master/contact.html).
> 
> `contact.md` exists
> 

See above.

> * > These [IOCCC guidelines](https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/guidelines.html) are version
> 
> `guidelines.md` exists

See above.

> 
> * > IMPORTANT: Be SURE to read the [IOCCC rules](https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/rules.html).
> 
> `next/rules.md` exists

See above.

> 
> * > The [Rule 2a](https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/rules.html#rule2a) size has increased from
> 
> `next/rules.md` exists - I do not recall any Markdown syntax for anchors like `#rule2a`, so it should just point to the `rules.md` , viewer left to scroll (if no contents table is generated).

They were added some days back. See [Rule 2a](https://ioccc-src.github.io/temp-test-ioccc/next/rules.html#rule2a) for example.

> 
> * > The [Rule 2b](https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/rules.html#rule2b) size has increased from
> 
> Similar to above point.
> 

See [Rule 2b](https://ioccc-src.github.io/temp-test-ioccc/next/rules.html#rule2b).


> The above are just some of the links I found while reviewing `next/guidelines.md` just at the start! I think this issue pervades throughout.
> 

Hopefully the replies help out.

> `Don't be the missing link.`

**Comment by SirWumpus** [comment]
> The rule is that if there is a html file then the link should refer to the html file.

I disagree.  If I'm reading a `.md` file, I should follow `.md` files, unless no such file exists ESPECIALLY while visiting documentation on GitHub.   A clear example that prompted this issue while reading `next/guidelines.md` was click on `contacts.html` only to see the `.html` source.  If that link had been `contacts.md`, then GitHub would have rendered it for viewing.

> No there should not be: some html files in some entries are provided by the author that cannot be generated by markdown.

If there is only an `.html` file for viewing (no markdown) then fine, link to it, but there will be display issues across GitHub.

> If they're generated by markdown they aren't duplicate - we just have to run the right rules to update them.

Hmm.   But you maintain some manifest manually and I know how those can get out of date having done similar for [libsnert](http://SirWumpus/libsnert).

Maybe the generation of the `.html` files from markdown should be part of a GitHub CI/CD workflow. 

> Yes but the markdown files, when generated to html, then link to the html files. See https://ioccc-src.github.io/temp-test-ioccc/index.html for the actual page.

Converting a markdown file from `.md` to `.html` should similarly convert the links from .md to .html.  My concern is within markdown file I want stay within markdown files assuming I'm viewing them via GitHub, NOT the `ioccc.org` website.

**Comment by xexyl** [comment]
> > The rule is that if there is a html file then the link should refer to the html file.
> 
> I disagree. If I'm reading a `.md` file, I should follow `.md` files, unless no such file exists ESPECIALLY while visiting documentation on GitHub. A clear example that prompted this issue while reading `next/guidelines.md` was click on `contacts.html` only to see the `.html` source. If that link had been `contacts.md`, then GitHub would have rendered it for viewing.
> 
> > No there should not be: some html files in some entries are provided by the author that cannot be generated by markdown.
> 
> If there is only an `.html` file for viewing (no markdown) then fine, link to it, but there will be display issues across GitHub.
> 
> > If they're generated by markdown they aren't duplicate - we just have to run the right rules to update them.
> 
> Hmm. But you maintain some manifest manually and I know how those can get out of date having done similar for [libsnert](http://SirWumpus/libsnert).
> 
> Maybe the generation of the `.html` files from markdown should be part of a GitHub CI/CD workflow.
> 
> > Yes but the markdown files, when generated to html, then link to the html files. See https://ioccc-src.github.io/temp-test-ioccc/index.html for the actual page.
> 
> Converting a markdown file from `.md` to `.html` should similarly convert the links from .md to .html. My concern is within markdown file I want stay within markdown files assuming I'm viewing them via GitHub, NOT the `ioccc.org` website.

Talk to Landon about this then. But there's no good way to satisfy both and the website looks much nicer. Also more people know about the IOCCC website than the GitHub repo.

The repo is what forms the website so how could it refer to the markdown but correctly link to the html files?

Some files do link to GitHub: those that are code or might have syntax highlighting (shell scripts, C files, Makefiles etc.).

**Comment by xexyl** [comment]
> Anyway I'm not saying you're wrong - just saying how it was decided. I kind of like the look of GitHub rendering too but now that I've seen the website more I quite like it a lot. FWIW I did not decide on this either way but I do like how it ended up, personally.

... by which I mean I didn't come up with the method but I quite like the result. 

One of the purposes of the repo was to help construct the website. 

BTW: we have also encountered issues with GitHub rendering that are not problems with the markdown but GitHub itself. So there's that. 

I understand the seemingly odd decision to have markdown files link to html files but since it's meant to be a website it works out. 

Maybe there should be an FAQ about this? I don't know. Anyway that's what it is anyway.

**Comment by xexyl** [comment]
# A 'solution'

If this is done it should definitely NOT be done until after 'things are in order' as the overhead would slow down an already slow process. But it would solve the problem, as far as it could. Remember that the README.md files and other markdown files do not have everything in them that the html files have: so the README.md file would not have the manifest.

Still it would probably be possible to change all the `\.html$` references to to `\.d$` (with the exception of files where there is no markdown) and then the scripts could be changed to, when passing to `pandoc(1)` (etc.) use `sed(1)` to change the `\.md$` to `.html`.

It would, as said above, not give everything, but it would possibly make it so that links work in GitHub and still have the website work too, again with the caveat that the markdown files in GitHub would not have everything they are supposed to: nor could they.

I don't know if it's worth it or if it's wanted but it would probably solve the problem.

Just a thought. But for now it can't be done as it would slow things down too much: assuming it's worth doing at all of course.

**Comment by xexyl** [comment]
> # A 'solution'
> If this is done it should definitely NOT be done until after 'things are in order' as the overhead would slow down an already slow process. But it would solve the problem, as far as it could. Remember that the README.md files and other markdown files do not have everything in them that the html files have: so the README.md file would not have the manifest, for one example thing of others, and other markdown files would not have everything the html files have either.
> 
> Still it would probably be possible to change all the `\.html$` references to to `\.md$` (with the exception of files where there is no markdown) and then the scripts could be changed to, when passing to `pandoc(1)` (etc.) use `sed(1)` to change the `\.md$` to `.html`. This is assuming, of course, that `pandoc(1)` reads from `stdin`.
> 
> It would, as said above, not give everything, but it would possibly make it so that links work in GitHub and still have the website work too, again with the caveat that the markdown files in GitHub would not have everything they are supposed to: nor could they.
> 
> I don't know if it's worth it or if it's wanted but it would probably solve the problem.
> 
> Just a thought. But for now it can't be done as it would slow things down too much: assuming it's worth doing at all of course.

Another problem btw: the markdown files have `%%TOKEN%%` for so the markdown files would have those and the links would not be okay (I think). So that's something to consider too and maybe reason to not do this. But anyway for the time being this cannot be done, if it can be at all (where 'can be' == 'should be').

**Comment by xexyl** [comment]
One of the other problems, a problem with GitHub rendering, is that markdown like:

```markdown
<div id="naqs">
### NAQs/IAQs (Never/Infrequently Asked Questions)
</div>  
```

... which is perfectly valid markdown results in not showing the heading in GitHub. Now maybe a blank line after the `<div>` and `</div>` would solve the problem but I don't know if that's the case. In my mind if it would it might be worth it down the road, maybe, just to make it look okay in GitHub, but that's another matter entirely and just an example with rendering with GitHub not being right. Of course there are different renderers ....

**Comment by xexyl** [comment]
An example of what happens when you click on a link with `%%REPO_URL%%`:

![Screenshot 2024-07-02 at 09 00 52](https://github.com/ioccc-src/temp-test-ioccc/assets/53008573/76be1cbb-e870-41ec-8931-88501d94f23b)


So as you can see it's not as simple as changing the `.html` to `.md` after all. Anyway those are some thoughts. Must leave now. Cheers.

**Comment by lcn2** [comment]
Markdown files are used (along with some JSON data) to generate HTML content.  It is the HTML content that people will use to view the official IOCCC web site, not markdown source.

There is a reason why HTML source has lines of the form:

```html
...

<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
<!-- !!! DO NOT MODIFY THIS FILE - This file is generated by a tool !!! -->
<!-- !!! DO NOT MODIFY THIS FILE - This file is generated by a tool !!! -->
<!-- !!! DO NOT MODIFY THIS FILE - This file is generated by a tool !!! -->
<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

<!-- END: this line ends content from: inc/head.default.html -->

<!-- -->
<!-- This web page was formed via the tool: bin/gen-top-html.sh -->
<!-- The content of main section of this web page came from: contact.md -->
<!-- -->

<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
<!-- !!! Do not modify this web page, instead modify the file: contact.md !!! -->
<!-- !!! Do not modify this web page, instead modify the file: contact.md !!! -->
<!-- !!! Do not modify this web page, instead modify the file: contact.md !!! -->
<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

<!-- Markdown content was converted into HTML via the tool: bin/md2html.sh -->

<!-- START: this line starts content from: inc/body.default.html -->

...
```

Nearly all HTML content on the web site is generated.  Where markdown data (and sometimes JSON data) is used to generate HTML content, the markdown content is not intended for humans to read on the web site.  We regard markdown as the "nroff MAN source" whereas people read the HTML ("the CAT page").

While one might find an inventory link to a markdown file, that link sends you into the GitHub repo for a reason: the markdown file is part of the **source** that is used to generate HTML content.    There is no web link to the `contact.md` file, for example, within the web site because the content for people to read in `content.html`.    Sure, someone can construct a URL to look at the markdown file, but the web page tree won't because the markdown content is not what people should be reading.

Reading markdown content on the site is like reading the `/usr/share/man/man1/ls.1` file when `man ls` is the intended content to be viewed.

There is no inconsistency here.  Links within the markdown content used to generate web pages are intended for the HTML (that `pandoc(1)` generates and `bin` tools generate).

While we appreciate bringing this to our attention. we must with respect close this issue with a:

```
INABIAF: It's not a bug it's a feature :-)
```

**Comment by SirWumpus** [comment]
Didn't mean to put anyone's nose out of joint.  I'm just in the habit of using the GitHub repo for official reference documentation (mine and third parties).  Often smaller projects don't have a web site, so the only doc is what is in the repository so being able to view and navigate that is important as a developer.
