### ISSUE TITLE
Bug: bin/csv2entry.sh removes JSON \uxxxx strings from JSON files

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/temp-test-ioccc#2691]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

When running `make csv2entry` any JSON `\uxxxx` strings are undone, changing it to the decoded string.

### What you expect

It should be kept as `\uxxxx`.

### Environment

- OS: n/a
- Device: n/a
- Compiler: n/a

### Anything else?

At a **VERY QUICK** guess the script might need to parse the strings `\uxxxx` and then retain them. But this is just a guess.

I would look at this but I am trying to rush the html files and since one can just undo (`git checkout`) the incorrect files this is not the biggest deal if one is aware of the problem. Nonetheless it should be fixed.

**Comment by xexyl** [comment]
Hmm .... I wonder actually. Maybe it's the script that converts award titles to CSV ? (If there is one .. don't remember but I have to continue the html files.)

**Comment by lcn2** [comment]
> Hmm .... I wonder actually. Maybe it's the script that converts award titles to CSV ? (If there is one .. don't remember but I have to continue the html files.)

`bin/entry2csv.sh`

**Comment by xexyl** [comment]
> > Hmm .... I wonder actually. Maybe it's the script that converts award titles to CSV ? (If there is one .. don't remember but I have to continue the html files.)
> 
> `bin/entry2csv.sh`

Okay. Perhaps you can fix this so I can continue the html files?

**Comment by lcn2** [comment]
Working in this issue ...

So we have \uxxxx strings in:

- 2000/bmeyer/.entry.json
- 2020/kurdyukov4/.entry.json
- author/Anton_Algmyr.json
- author/Ondrej_Adamovsky.json

So when we do:

```sh
make entry2csv
```

Those JSON files (and the others) are converted into:

- author_wins.csv
- manifest.csv
- summary.csv
- year_prize.csv

What we see with the CSV files is that the JSON strings are decoded.

For example in `year_prize.csv` we find:

```csv
2020_kurdyukov4,Best abuse of lámatyávë
```

That was decoding of the award from `2020/kurdyukov4/.entry.json`:

```json
...
    "award" : "Best abuse of l\u00e1maty\u00e1v\u00eb",
...
```

And that is correct because the resulting `2020/kurdyukov4/index.html` shows the proper JSON decoded Unicode characters.

That all works as expected.

Now when we execute:

```sh
make csv2entry
```

we convert those CSV files back into JSON files.  That is, we convert the data found in:

- author_wins.csv
- manifest.csv
- summary.csv
- year_prize.csv

Data that was produced by the previous `make entry2csv` run, into the various `.entry.json` files and the various `author/author_handle.json` files.  Well to be more precise, the `make csv2entry` generates each JSON file and IF AND ONLY IF they are different the JSON file is replaced.

HOWEVER ...

For the award, the \uxxxx strings was modified!  So there is a bug/mis-feature.

```diff
diff --git a/2020/kurdyukov4/.entry.json b/2020/kurdyukov4/.entry.json
index f7741ae9f..6e9bfa7be 100644
--- a/2020/kurdyukov4/.entry.json
+++ b/2020/kurdyukov4/.entry.json
@@ -1,7 +1,7 @@
 {
     "no_comment" : "mandatory comment: because comments were removed from the original JSON spec",
     "entry_JSON_format_version" : "1.2 2024-09-25",
-    "award" : "Best abuse of l\u00e1maty\u00e1v\u00eb",
+    "award" : "Best abuse of lámatyávë",
     "year" : 2020,
     "dir" : "kurdyukov4",
     "entry_id" : "2020_kurdyukov4",
```

We will work on a fix.

**Comment by xexyl** [comment]
Thanks! I'll very possibly be leaving shortly. It is unclear but I might have a bit of time later on today to work on 2014. I do feel good about the progress I made though. I hope tomorrow to at least get to 2018 but we shall see. What is certain is you working on this instead of me will help out.

Good luck with this! Also I hope the symptoms are lessening!

**Comment by lcn2** [comment]
With commit 567e6541f85df617ee359f698f90965cea29ef08 we believe this issue has been resolved.

**Comment by xexyl** [comment]
Thanks! Back tomorrow. Good day and best wishes with your recovery!
